language: python
python:
    - 3.6
install:
    - pip install mypy
    - pip install -e .[docs]
script:
    - mypy --ignore-missing-imports oj
    - make -C docs html
    - python setup.py test
branches:
    only:
        - master
